In [1]:
from sklearn.preprocessing import LabelEncoder

#label encoding은 카테고리 feature를 숫자 값으로 변환하는 것

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

#LabelEncoder로 객체를 생성한 후, fit()과 transform()으로 label encoding 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환 값: ', labels)

인코딩 변환 값:  [0 1 4 5 3 3 2 2]


In [2]:
print('인코딩 클래스: ', encoder.classes_)

인코딩 클래스:  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

#숫자 값으로의 변환을 위해 LabelEncoder를 거친 데이터 활용
labels = labels.reshape(-1, 1)

#OneHotEncoding 적용
ohe = OneHotEncoder()
ohe.fit(labels)
ohe_labels = ohe.transform(labels)
print('OneHotEncoding 데이터')
print(ohe_labels.toarray())
print('OneHotEncoding 데이터 차원')
print(ohe_labels.shape)

OneHotEncoding 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
OneHotEncoding 데이터 차원
(8, 6)


In [5]:
import pandas as pd

df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기','믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0